; PlatformIO Project Configuration File
; Targets: LPC1768, FRDM-K64F (mbed), Adafruit ESP32-S3 TFT Feather (Arduino)

[common]
monitor_speed = 38400

[env:lpc1768]
platform      = nxplpc
board         = lpc1768
framework     = mbed
build_flags   = -DHAL_MBED -DBOARD_LPC1768
monitor_speed = ${common.monitor_speed}

[env:frdm_k64f]
platform      = freescalekinetis
board         = frdm_k64f
framework     = mbed
build_flags   = -DHAL_MBED -DBOARD_FRDM_K64F
monitor_speed = ${common.monitor_speed}

[env:esp32s3_tft]
platform      = espressif32
board         = adafruit_feather_esp32s3_tft
framework     = arduino
build_flags   = -DHAL_ARDUINO -DBOARD_ESP32S3_TFT
monitor_speed = ${common.monitor_speed}
